version: "3.8"
services:
  gs-livm:
    build: .
    volumes:
      - .:/workspace/GS-LIVM
    working_dir: /workspace/GS-LIVM
    command: bash
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
