name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CCACHE_DIR: ~/.ccache
    steps:
      - uses: actions/checkout@v4

      - name: Cache apt
        uses: actions/cache@v4
        with:
          path: /var/cache/apt/archives
          key: ${{ runner.os }}-apt-${{ hashFiles('**/package.xml') }}
          restore-keys: ${{ runner.os }}-apt-

      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-ccache-${{ github.sha }}
          restore-keys: ${{ runner.os }}-ccache-

      - name: Setup ROS
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: noetic

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-catkin-tools clang-format cppcheck
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y

      - name: Build
        run: catkin build

      - name: Run tests
        run: |
          catkin run_tests
          catkin_test_results

      - name: clang-format
        run: |
          clang-format --version
          find src include -type f \( -name '*.h' -o -name '*.hpp' -o -name '*.cpp' \) | xargs clang-format -n

      - name: cppcheck
        run: |
          cppcheck --version
          cppcheck --error-exitcode=1 --enable=warning,style,performance,portability include src
